sudo: false
language: go

go:
- 1.7
- tip

before_install:
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/golang/lint/golint

script:
- go test -coverprofile=coverage.out ./compose
- go tool cover -func=coverage.out
- go test -coverprofile=coverage.out ./ecs
- go tool cover -func=coverage.out
- go test -coverprofile=coverage.out ./script
- go tool cover -func=coverage.out
- go test -race $(go list ./... | grep -v /vendor/)
